package hibernate.metier;

// Generated 22 févr. 2013 17:19:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Proprietaire generated by hbm2java
 */
public class Proprietaire implements java.io.Serializable
{

    private Integer idProprietaire;
    private String nomProprietaire;
    private String prenomProprietaire;
    private Set oeuvreprets = new HashSet(0);
    private Set oeuvreventes = new HashSet(0);

    public Proprietaire()
    {
    }

    public Proprietaire(String nomProprietaire)
    {
	this.nomProprietaire = nomProprietaire;
    }

    public Proprietaire(String nomProprietaire, String prenomProprietaire,
	    Set oeuvreprets, Set oeuvreventes)
    {
	this.nomProprietaire = nomProprietaire;
	this.prenomProprietaire = prenomProprietaire;
	this.oeuvreprets = oeuvreprets;
	this.oeuvreventes = oeuvreventes;
    }

    public Integer getIdProprietaire()
    {
	return this.idProprietaire;
    }

    public void setIdProprietaire(Integer idProprietaire)
    {
	this.idProprietaire = idProprietaire;
    }

    public String getNomProprietaire()
    {
	return this.nomProprietaire;
    }

    public void setNomProprietaire(String nomProprietaire)
    {
	this.nomProprietaire = nomProprietaire;
    }

    public String getPrenomProprietaire()
    {
	return this.prenomProprietaire;
    }

    public void setPrenomProprietaire(String prenomProprietaire)
    {
	this.prenomProprietaire = prenomProprietaire;
    }

    public Set getOeuvreprets()
    {
	return this.oeuvreprets;
    }

    public void setOeuvreprets(Set oeuvreprets)
    {
	this.oeuvreprets = oeuvreprets;
    }

    public Set getOeuvreventes()
    {
	return this.oeuvreventes;
    }

    public void setOeuvreventes(Set oeuvreventes)
    {
	this.oeuvreventes = oeuvreventes;
    }

}
