package hibernate.metier;

// Generated 22 fvr. 2013 17:19:52 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable
{

    private ReservationId id;
    private Adherent adherent;
    private Oeuvrevente oeuvrevente;
    private Date dateReservation;

    public Reservation()
    {
    }

    public Reservation(ReservationId id, Adherent adherent,
	    Oeuvrevente oeuvrevente, Date dateReservation)
    {
	this.id = id;
	this.adherent = adherent;
	this.oeuvrevente = oeuvrevente;
	this.dateReservation = dateReservation;
    }

    public ReservationId getId()
    {
	return this.id;
    }

    public void setId(ReservationId id)
    {
	this.id = id;
    }

    public Adherent getAdherent()
    {
	return this.adherent;
    }

    public void setAdherent(Adherent adherent)
    {
	this.adherent = adherent;
    }

    public Oeuvrevente getOeuvrevente()
    {
	return this.oeuvrevente;
    }

    public void setOeuvrevente(Oeuvrevente oeuvrevente)
    {
	this.oeuvrevente = oeuvrevente;
    }

    public Date getDateReservation()
    {
	return this.dateReservation;
    }

    public void setDateReservation(Date dateReservation)
    {
	this.dateReservation = dateReservation;
    }

}
